# Generated by Django 4.2.2 on 2023-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
