# Generated by Django 4.2.7 on 2023-11-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customer_birth_date_alter_customer_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='MEMBERSHIP_BRONZE', max_length=50),
        ),
    ]
